In [1]:
my_list=[1,2,3]

In [2]:
import numpy as np

In [10]:
np.arange(1,5)

array([1, 2, 3, 4])

In [11]:
my=[[0,1,2],[3,4,5],[6,7,8]]

In [12]:
np.array(my)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
np.arange(0,11,3)

array([0, 3, 6, 9])

In [25]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.linspace(0,5,3)

array([0. , 2.5, 5. ])

In [5]:
np.linspace(0,8,0)

array([], dtype=float64)

In [6]:
np.linspace(0,8,5)

array([0., 2., 4., 6., 8.])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5)

array([0.41786135, 0.91895037, 0.9329076 , 0.66398468, 0.86200349])

In [17]:
np.random.rand(5,5)

array([[0.20018307, 0.74433624, 0.31030465, 0.69855368, 0.81503488],
       [0.67007588, 0.05340897, 0.56099227, 0.20439294, 0.64362308],
       [0.6157452 , 0.02438874, 0.80410569, 0.67310619, 0.75878731],
       [0.98664076, 0.62086229, 0.77729373, 0.74408709, 0.65846975],
       [0.88392075, 0.4252152 , 0.78966236, 0.24345363, 0.56676282]])

In [20]:
np.random.randint()

array([[ 1.16635911e+00,  1.88829079e+00,  1.13098817e+00,
        -8.49754997e-01],
       [-1.86616509e-01, -1.51586081e-01,  6.49242465e-01,
        -2.52315357e-01],
       [-3.78756245e-01,  5.23073171e-01, -5.89341477e-01,
         8.75389521e-01],
       [ 8.44404856e-01,  8.28354060e-01, -2.85343270e-05,
        -9.36082899e-01]])

In [21]:
np.random.randint(1,10)

4

In [23]:
np.random.randint(1,10,10)

array([1, 8, 7, 6, 5, 3, 9, 1, 8, 6])

In [27]:

arr=np.arange(25)

In [28]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr=np.random.randint(0,50,10)

In [30]:
ranarr

array([13,  0, 31, 23,  8, 37, 48,  2, 12, 46])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
arr=np.arange(9)

In [39]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
are=np.arange(14)

In [49]:
are

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [50]:
ranarr

array([13,  0, 31, 23,  8, 37, 48,  2, 12, 46])

In [52]:
ranarr.argmax()

6

In [53]:
ranarr.max()

48

In [54]:
ranarr.min()

0

In [55]:
ranarr.argmin()

1

In [56]:
are.min()

0

In [57]:
are.max()

13

In [58]:
are.argmax()

13

In [59]:
arr.shape

(9,)

In [62]:
arr=np.arange(30)

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [64]:
arr.shape

(30,)