In [4]:
my_list=[1,2,3]

In [5]:
import numpy as np

In [6]:
arr=np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arrayis=[[1,2,3],[4,5,6],[7,8,9]]

In [11]:
arrayis

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(arrayis)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,10,7)

array([0, 7])

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [34]:
np.random.rand(5)

array([0.22528261, 0.17087885, 0.21797874, 0.10202983, 0.08647783])

In [36]:
np.random.rand(5,5)

array([[0.44611149, 0.75558257, 0.23439533, 0.0992787 , 0.12911573],
       [0.48853557, 0.95871088, 0.03942984, 0.27715143, 0.08982197],
       [0.29258963, 0.25562093, 0.09657324, 0.67117281, 0.59707534],
       [0.57893814, 0.33151548, 0.97494333, 0.55239352, 0.23056519],
       [0.60228145, 0.68209261, 0.73004815, 0.25997383, 0.11926852]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
arr = np.arange(25)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr=np.random.randint(0,50,10)

In [43]:
ranarr

array([46, 24,  9,  5, 43, 11, 44,  4, 41, 42])

In [44]:
arrt=np.random.randint(0,5,5)

In [45]:
arrt

array([2, 3, 2, 3, 2])

In [46]:
np.random.randint(0,4,10)

array([1, 2, 1, 3, 3, 2, 1, 1, 3, 0])

In [47]:
arr=np.arange(45)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [51]:
ranarr

array([46, 24,  9,  5, 43, 11, 44,  4, 41, 42])

In [50]:
ranarr.max()

46

In [56]:
ranarr.min()

2

In [57]:
ranarr

array([20, 11,  2,  2,  6, 33, 26, 33, 49, 42])

In [58]:
ranarr.argmax()

8

In [74]:
ranarr.argmin()

2

In [78]:
arr=arr.reshape(5,5)

In [81]:
arr.shape

(5, 5)

In [61]:
era=np.random.randint(0,5,10)

In [62]:
era

array([4, 0, 0, 4, 1, 4, 1, 1, 4, 4])

In [67]:
era.max()

4

In [71]:
era.argmax()

0

In [73]:
era.argmin()

1

In [82]:
arr.dtype

dtype('int32')

In [83]:
from numpy.random import randint

In [84]:
randint(2,10)

9