In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr[0:5]=100

In [18]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [20]:
arr=np.arange(0,11)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
slice_of_arr=arr[0:6]

In [23]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [25]:
slice_of_arr[:]=99

In [26]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [27]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
arr_copy = arr.copy()

In [30]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [32]:
arr_copy[:]=100

In [33]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [34]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])